# CC1: Particule dans un cyclotron
## Partie I

1. Créer un tableau contenant les instants de sortie des boucles "D" : $t_0$, $t_1$, ... jusqu'à $t_{50}$ inclus. 

Pour cela nous utiliserons la fonction $$t_n=n+\tau \sqrt{n}.$$ et on choisit $\tau=0.5$.





In [1]:
# importation des modules 
import numpy as np
import matplotlib.pyplot as plt

#condition initiales:
n = 50 #nombre d'instant de sortie
tau=0.5 # tau choisi

#definition de la fonction qui calculer les n valeurs de t
def tn(n):
    ''' fonction qui permet de calculer le temps tn'''
    return n+tau*np.sqrt(n)

l_tn=[] #creation d'une liste vide

#calcule des 50 valeurs de t 
for n in range(50):
    l_tn.append(tn(n))
    
#creation du tableau
t_tn= np.array(l_tn)

print(t_tn)
print( "nombre de valeur:", len(t_tn)) # verification qu'on a bien 50 valeurs 


[ 0.          1.5         2.70710678  3.8660254   5.          6.11803399
  7.22474487  8.32287566  9.41421356 10.5        11.58113883 12.6583124
 13.73205081 14.80277564 15.87082869 16.93649167 18.         19.06155281
 20.12132034 21.17944947 22.23606798 23.29128785 24.34520788 25.39791576
 26.44948974 27.5        28.54950976 29.59807621 30.64575131 31.6925824
 32.73861279 33.78388218 34.82842712 35.87228132 36.91547595 37.95803989
 39.         40.04138127 41.082207   42.122499   43.16227766 44.20156212
 45.24037035 46.27871926 47.31662479 48.35410197 49.39116499 50.4278273
 51.46410162 52.5       ]
nombre de valeur: 50


 2. Vérifier que $t_1=1.5$, $t_4=5$, $t_9=10.5$, $t_{16}=18$, et $t_{25}=27.5$ avec des opérateurs booléens.

In [2]:
#verifitvation des differentes valeurs pour tn 

print("t1=",t_tn[1],"t4=", t_tn[4],"t9=", t_tn[9],"t16=", t_tn[16],"t25=", t_tn[25])


t1= 1.5 t4= 5.0 t9= 10.5 t16= 18.0 t25= 27.5


les valeurs sont correctes.

3. Calculer les valeurs de $v_x$ et $v_y$ en fonction du temps pour $t$ variant de $t_2−1$ à $t_2$. Vous utiliserez un échantillonage suffisant pour le temps $t$, dans un tableau distinct de celui de la question précédente. Faire de même pour $t$ variant de $t_4-1$ à $t_4$. 


In [ ]:
#definition de epsilon 
eps_n=(-1)**n
# creation des listes vides
Vy=[]
Vx=[]
# fonction pour calculer les vitesses
def Vy2(n,t):
    ''' fonction qui permet de calculer la vitesse pour 𝑡 variant de 𝑡𝑛+1−1 à 𝑡𝑛+1 '''
    return -(eps_n)*np.sqrt(n+1)*np.cos(np.pi*(t-2.7))
        
def Vx2(n,t):
    ''' fonction qui permet de calculer la vitesse pour 𝑡 variant de 𝑡𝑛+1−1 à 𝑡𝑛+1 '''
    return eps_n*np.sqrt(n+1)*np.sin(np.pi*(t-2.7))

for t in range(1,4):
    Vy.append(Vy2(1,t))

for t in range(1,4):
    Vx.append(Vx2(1,t))
    
print(Vy)
    
plt.plot(Vx,t_tn)
plt.plot(Vy,t_tn)
plt.title('vx et vy en fonction de 𝑡 pour 𝑡 variant de t2-1 a t2')
plt.xlabel('temps')
plt.ylabel('vx et vy')
plt.grid()
plt.show()